name: Upload File to Supabase

on:
  push:
    paths:
      - public/uploads/**

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload all files in public/uploads to Supabase
        run: |
          for file in $(find public/uploads -type f); do
            filename=$(basename "$file")
            curl -X POST "${SUPABASE_URL}/storage/v1/object/${BUCKET}/${filename}" \
              -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
              -H "Content-Type: $(file -b --mime-type "$file")" \
              --data-binary @"$file"
          done
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          BUCKET: ${{ secrets.SUPABASE_BUCKET }}
